### ISSUE TITLE
Not work Linq queries with DateTimeOffset

### ISSUE THREAD

**Issue by UlykinAndrey** [oliversturm/xpo-sqlserver-datetimeoffset#1]
Hello, i need DateTimeOffset support in my application. Thank you for example. But i need using LINQ for
DateTimeOffset datatime. I am do some modifications.

using (UnitOfWork uow = new UnitOfWork()) 
{
      var data = new XPQuery<TimeData>(uow).Where(td => td.Dto.Date > DateTime.Now.Date).ToList();
  

And code dont work now. Issue in td.Dto.Date property access. But i need select from DB all rows by Date (without time). How can i solve this task?

**Comment by tkouba** [comment]
You can use this
`var data = new XPQuery(uow).Where(td => td.Dto >= DateTime.Today.AddDay(1)).ToList();`
it selects all records from tomorrow 00:00, for today use this
`var data = new XPQuery(uow).Where(td => td.Dto >= DateTime.Today && td.Dto < DateTime.Today.AddDay(1)).ToList();`
for another ranges is same. In some cases we are using second column with date only value.

**Comment by oliversturm** [comment]
I haven't tried it, but I expect @tkouba 's suggestion to work. I think it would be technically possible to make @UlykinAndrey 's code work as well, but that would require extending the translation logic of the LINQ provider to generate some special syntax (I assume it exists) that makes SQL server dig into the data structure of the Dto field and perform the query on one part of the information. Not an easy task, and I wouldn't want to tackle it as long as there are other syntactic variations of the query that do the job.

I'm going to close this issue, but feel free to re-open in case the proposed solution doesn't work for you.
